---
# descrever a máquina em que se vai trabalhar
- hosts: terraformansible
  # tarefas a serem executadas
  # dividir as tarefas em blocos: criação de arquivos; executar no shell; ...

  # Colocando Phyton3 e Virtualenv
  tasks:
  - name: instalando o Python3 e o virtualenv
    apt:
      # é o gerenciador de pacotes do ubuntu, mas funciona com outras distros.
      pkg:
        - python3
        # - python3.9
        - virtualenv
      update_cache: yes
      # atualiza os repositórios (apt update!)
    become: yes
    # become: yes é para rodar as tasks como sudo!

  - name: Clone a github repository
    # git: XXX este comando ou o comando abaixo para clonar repositório
    ansible.builtin.git:
      repo: https://github.com/guilhermeonrails/clientes-leo-api.git
      # local no github onde está o projeto adicionado do sufixo .git
      dest: /home/ubuntu/virtualenv/
      # destino na máquina
      version: master
      # version da branch que estamos utilizando
      # clone: yes  XXX este comando ou o comando acima para clonar repositório
      # update: yes  XXX este comando ou o comando acima para clonar e atualizar repositório
  # instalando depedencias com pip (Django e Django Rest)
  - name: instalando depedencias com pip (Django e Django Rest)
    pip:
      virtualenv: /home/ubuntu/virtualenv/venv
      # O ansible liga a virtualenv com o comamdo abaixo ou acima
      # passando o nome do pacotes
      name:
        - django
        - djangorestframework
        # fazendo o Django aparecer como web site na internet
        # alterando o parametro host do arquivo settings.py se ele existir
  - name: alterando o hosts do arquivo settings
    lineinfile:
      path: /home/ubuntu/virtualenv/setup/settings.py
      # expressão regular
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      # backrefs diz que se ele não encontrar ALLOWED_HOSTS no nosso arquivo
      # ele não vai mexer no arquivo!
      backrefs: yes
